[package]
name = "rb-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rb-hir.workspace = true
rb-mir.workspace = true
rb-value.workspace = true
rb-codegen.workspace = true
rb-codegen-opt.workspace = true
rb-codegen-x86.workspace = true

smallvec = "1.15.1"
